---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: couch-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: couchdb
    spec:
      containers:
      - name: couchdb
        image: hyperledger/fabric-couchdb
        ports:
        - containerPort: 5984
          name: http
        env:
        - name: COUCHDB_USER
          value: ""
        - name: COUCHDB_PASSWORD
          value: ""
