---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: couchdb
spec:
    replicas: 1
    template:
        metadata:
            labels:
                tier: db
        spec:
            terminationGracePeriodSeconds: 10
            containers:
                - name: couchdb
                  image: couchdb:1.6
                  ports:
                      - containerPort: 5984
                        name: http
                  env:
                      - name: COUCHDB_USER
                        value: ""
                      - name: COUCHDB_PASSWORD
                        value: ""