---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-ca-external
  labels:
    run: blockchain-ca-external
spec:
  type: LoadBalancer
  selector:
    name: ca
  ports:
  - protocol: TCP
    targetPort: 7054
    port: 84
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer-external
  labels:
    run: blockchain-orderer-external
spec:
  type: LoadBalancer
  selector:
    name: orderer
  ports:
  - protocol: TCP
    targetPort: 31010
    port: 85
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-org1peer1-external
  labels:
    run: blockchain-org1peer1-external
spec:
  type: LoadBalancer
  selector:
    name: org1peer1
  ports:
  - protocol: TCP
    targetPort: 30110
    port: 80
    name: grpc
  - protocol: TCP
    targetPort: 30111
    port: 81
    name: events