---
apiVersion: v1
kind: Service
metadata:
  name: blockchain
  labels:
    run: blockchain
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    targetPort: 30054
    port: 7054
    name: ca
  - protocol: TCP
    targetPort: 31010
    port: 7050
    name: orderer
  - protocol: TCP
    targetPort: 30110
    port: 7051
    name: peer
  - protocol: TCP
    targetPort: 30111
    port: 7053
    name: events