---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-ca-lb
  labels:
    run: blockchain-ca-lb
spec:
  type: LoadBalancer
  selector:
    name: ca
  ports:
  - protocol: TCP
    nodePort: 30054
    targetPort: 7054
    port: 80
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer-lb
  labels:
    run: blockchain-orderer-lb
spec:
  type: LoadBalancer
  selector:
    name: orderer
  ports:
  - protocol: TCP
    nodePort: 31010
    targetPort: 31010
    port: 81
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-org1peer1-lb
  labels:
    run: blockchain-org1peer1-lb
spec:
  type: LoadBalancer
  selector:
    name: org1peer1
  ports:
  - protocol: TCP
    nodePort: 30110
    targetPort: 30110
    port: 82
    name: grpc
  - protocol: TCP
    nodePort: 30111
    targetPort: 30111
    port: 83
    name: events