---
apiVersion: v1
kind: Service
metadata:
  name: blockchain
  annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"  
  labels:
    run: blockchain
spec:
  type: LoadBalancer
  selector:
    app: bc
  ports:
  - protocol: TCP
    targetPort: 7054
    port: 7054
    name: ca
  - protocol: TCP
    targetPort: 7050
    port: 7050
    name: orderer
  - protocol: TCP
    targetPort: 7051
    port: 7051
    name: peer
  - protocol: TCP
    targetPort: 7053
    port: 7053
    name: events